### ISSUE TITLE
Color Normalization Issue

### ISSUE THREAD

**Issue by mingloo** [GengDavid/pytorch-cpn#10]
Hi @GengDavid,

I've found the self.pixel_means is changed in every iteration when calling __getitem__ due to modification of mean variable in color_normalize function. As a result, our expected color normalization will not take effect after several samples iterations because the mean value decreases to [0, 0, 0].

This issue infects both training and testing phase.

See detailed printed log below:

checking pixel means __init__: [122.7717 115.9465 102.9801]
=> loaded checkpoint 'checkpoint/epoch32checkpoint.pth.tar' (epoch 32)
testing...
checking pixel means __getitem__: [122.7717 115.9465 102.9801]
checking pixel means __getitem__: [0.48145765 0.45469216 0.40384353]
checking pixel means __getitem__: [0.00188807 0.00178311 0.0015837 ]
checking pixel means __getitem__: [7.40419296e-06 6.99257450e-06 6.21058869e-06]
checking pixel means __getitem__: [2.90360508e-08 2.74218608e-08 2.43552498e-08]

Please help to double check it.

**Comment by GengDavid** [comment]
I have merge your PR and update the models. Thanks again.
