### ISSUE TITLE
questions about test.py

### ISSUE THREAD

**Issue by Liz66666** [GengDavid/pytorch-cpn#12]
hi, thanks for your pytorch code!
I have seen your code about test a model, but I don't know why 4*x and 4*y should plus 2(line 115 and 116)?
And I have also seen that tf-version plus 2 too.
Thanks!
https://github.com/GengDavid/pytorch-cpn/blob/48696a9203ad6dac78cf7e9e74b572b77f30aad9/256.192.model/test.py#L110-L117

**Comment by GengDavid** [comment]
Because we want to recover the precision lost costed in the generation of label maps.
Also can refer to [this issue](https://github.com/chenyilun95/tf-cpn/issues/13#issue-318823289).

**Comment by Liz66666** [comment]
thanks for your reply!
