### ISSUE TITLE
about the number of the output keypoints?

### ISSUE THREAD

**Issue by lunalulu** [GengDavid/pytorch-cpn#16]
hi, thanks for your pytorch code!
I have seen your code about test a model,but i dont know why the number of the output keypoints is always 51(17 keypoints), The way I print it is:
              if len(single_result) != 0:

                        single_result_dict['image_id'] = int(ids)

                        single_result_dict['category_id'] = 1

                        single_result_dict['keypoints'] = single_result

                        **print(len(single_result_dict['keypoints']))**

                        single_result_dict['score'] = float(det_scores[b]) * v_score.mean()

                        full_result.append(single_result_dict)

And I notice that the keypoints coodr in the resulting file(result.json) don't have zero values.

**Comment by GengDavid** [comment]
Sorry for the late reply. 
For each point, there're three values: (x, y, visibility). Please refer to [coco website](http://cocodataset.org/#format-results) for details.

**Comment by GengDavid** [comment]
Seems the problem has been solved. Close this issue.
