### ISSUE TITLE
an unexpected keyword argument

### ISSUE THREAD

**Issue by aidarikako** [GengDavid/pytorch-cpn#18]
I ran the train.py,but got a error.'TypeError: __init__() got an unexpected keyword argument 'align_corners''.It occured at globalNet.py,line 56.
I don't know how to fix it,can you help me?thank you

**Comment by GengDavid** [comment]
This project is now supporting PyTorch version >= 0.4.1. If your version is lower than that (PyTorch 0.3.1 for example), there is no ```align_corners``` parameter for upsample operation. And you need to do other adjustments to use this code.  
I guess updating PyTorch version could be more convenient.

**Comment by Cronusf** [comment]
When I downloaded the model, there was an error and I couldn't download it.
Can you send me a trained three network models to my mailbox? 1227597758@qq.com. Thanks very much

**Comment by aidarikako** [comment]
> This project is now supporting PyTorch version >= 0.4.1. If your version is lower than that (PyTorch 0.3.1 for example), there is no `align_corners` parameter for upsample operation. And you need to do other adjustments to use this code.
> I guess updating PyTorch version could be more convenient.

Thank you for your help.I find that my PyTorch version=0.3.1.I'll upgrade it and try again.

**Comment by GengDavid** [comment]
Seems you have solved the problem. I'll close this issue. If you still have any problem on it, feel free to reopen it.
