### ISSUE TITLE
about the cpu utilized percent

### ISSUE THREAD

**Issue by songyonger** [GengDavid/pytorch-cpn#28]
When I run the train. py ,the cpu  utilized percent is more than 300%. How can I solve the problem?

**Comment by GengDavid** [comment]
Maybe you can adjust the number of workers in dataloader by changing [this](https://github.com/GengDavid/pytorch-cpn/blob/48696a9203ad6dac78cf7e9e74b572b77f30aad9/256.192.model/train.py#L153) parameter.

**Comment by songyonger** [comment]
@GengDavid  thanks!
