### ISSUE TITLE
where is the file of "COCO_2017_train.json" ,"COCO_2017_val.json", "val_dets.json"? i can't find them in the coco dataset

### ISSUE THREAD

**Issue by chjXu** [GengDavid/pytorch-cpn#37]
FileNotFoundError: [Errno 2] No such file or directory: '/media/agent/data/xcj/pytorch-cpn/256.192.model/../data/COCO2017/annotations/COCO_2017_train.json'

**Comment by Michaelszeng** [comment]
How did you solve the issue? I have the same question.

Edit: I just missed the step where you run python `label_transform.py`. This program creates the files COCO_2017_val.json and COCO_2017_train.json
